In [2]:
#Import Libraries and Load Dataset
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("netflix_pyml.csv")

# Display first 5 rows
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

Dataset understanding

In [9]:
#Q1. Load the dataset and display the first five records.
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [5]:
#Q2. Determine the number of rows and columns.
df.shape

(750, 10)

In [6]:
#Q3. Display all column names.
df.columns

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [7]:
#Q4. Identify numerical and categorical features.
print("Numerical Columns:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Columns:")
print(df.select_dtypes(include=['object']).columns)

Numerical Columns:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Columns:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [8]:
#Q5. Check whether the dataset contains missing values.
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

Part B: Exploratory Data Analysis

In [11]:
#Q6. Calculate the average age of users.
df["Age"].mean()

np.float64(41.824)

In [12]:
#Q7. Determine the average watch hours per week.
df["WatchHoursPerWeek"].mean()

np.float64(14.236)

In [13]:
#Q8. Find the average monthly spending of users.
df["MonthlySpend"].mean()

np.float64(689.9053333333334)

In [14]:
#Q9. Count the number of users in each subscription category.
df["SubscriptionType"].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [15]:
#Q10. Determine the percentage of users who renewed their subscriptions.
renewed_percentage = (df["SubscriptionRenewed"]=="Yes").mean()*100
renewed_percentage

np.float64(46.266666666666666)

Part C: Data Preparation

In [16]:
#Q11. Convert categorical features into numerical form.
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

encoder = LabelEncoder()

for col in ["Gender","SubscriptionType","FavoriteGenre","SubscriptionRenewed"]:
    df_encoded[col] = encoder.fit_transform(df_encoded[col])

df_encoded.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [17]:
#Q12. Define the feature set (X) and target variable (y) for subscription renewal prediction.
X = df_encoded.drop("SubscriptionRenewed", axis=1)
y = df_encoded["SubscriptionRenewed"]

print(X.shape)
print(y.shape)

(750, 9)
(750,)

In [18]:
#Q13. Split the dataset into training and testing sets.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(600, 9)
(150, 9)

Part D: Decision Tree Classification

In [19]:
#Q14. Train a Decision Tree model to predict whether a user will renew their subscription.
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [20]:
#Q15. Evaluate the model using accuracy.
from sklearn.metrics import accuracy_score

dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.5666666666666667

In [21]:
#Q16. Generate and interpret the confusion matrix.
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, dt_pred)

print(cm)

[[50 32]
 [33 35]]

Part E: K-Nearest Neighbors (KNN)

In [22]:
#Q17. Train a KNN classifier with K = 5.
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

In [23]:
#Q18. Compare the accuracy of KNN with the Decision Tree model.
knn_accuracy = accuracy_score(y_test, knn_pred)

print("Decision Tree Accuracy:", dt_accuracy)
print("KNN Accuracy:", knn_accuracy)

Decision Tree Accuracy: 0.5666666666666667
KNN Accuracy: 0.6

Part F: Linear Regression

In [24]:
#Q19. Train a Linear Regression model to predict monthly spending.
from sklearn.linear_model import LinearRegression

X_reg = df_encoded.drop("MonthlySpend", axis=1)
y_reg = df_encoded["MonthlySpend"]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

lr_model = LinearRegression()

lr_model.fit(X_train_reg, y_train_reg)

LinearRegression()

In [25]:
#Q20. Predict the monthly spending for a new user and interpret the result.
new_user = [[
    2000,   # UserID
    30,     # Age
    1,      # Gender
    2,      # SubscriptionType
    20,     # WatchHoursPerWeek
    3,      # DevicesUsed
    1,      # FavoriteGenre
    15,     # AdClicks
    1       # SubscriptionRenewed
]]

prediction = lr_model.predict(new_user)

print("Predicted Monthly Spending = ₹", prediction[0])

Predicted Monthly Spending = ₹ 1332.7642462915585

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Business Reflection Questions
1. Which factors appear to influence subscription renewal the most?  
ans=>Subscription Type,Watch Hours Per,Week,Monthly Spending,Devices Used,Ad Clicks

2. Why is subscription renewal a classification problem?  
ans=>because model need to predict only class as targeted variable have 2 type(yes,no)

3. Why is monthly spending a regression problem?  
ans=>since output will be continous,so regression will be used

4. Which algorithm performed better for renewal prediction?
ams=>knn accuracy

5. How could the platform use these predictions to improve customer retention?
Netflix can
Identify users likely to cancel.
Offer personalized discounts.
Recommend relevant content.
Improve customer engagement.
Increase customer retention.
Increase revenue through targeted marketing.